export const setting = {
  general: {
    reconnect_interval: 5000,
    table_update_interval: 800,
    split_ratio: 20,
  },
  history: {
    picker_increment: 10, // minutes
    picker_period: 6, // hours
    refresh_interval: 60, // seconds
  },
  segment_geometries: {
    D: {
      length: 1,
      shortSide: 1,
      longSide: 1,
    },
    E: {
      length: 1085,
      shortSide: 650,
      longSide: 650,
    },
    U: {
      length: 1870,
      shortSide: 650,
      longSide: 1000,
    },
    S: {
      length: 1430,
      shortSide: 610,
      longSide: 1200,
    },
  },
  map: {
    show_minimap: false,
    show_point_labels: false,
    show_direction_arrows: true,
    show_segments: true,
    show_stations: true,
    show_buffers: true,
    show_mtls: true,
    show_vehicles: true,
    show_groups: true,
    show_clusters: true,
    show_expected_path: false,
    vehicle_scale: 8,
    location_scale: 30,
    direction_arrow_scale: 5,
    map_rotation: 0,
    snap_to_grid_distance: 500, // mm
    minimumSegmentLength: 500, // mm
    minimap_size_limit: 150, // pixels
    num_ticks: 20,
    vehicle_stale: 600, // s
    speed_straight: 3600, // m/s
    speed_curve: 800, // m/s
    scale_offset_x: 50,
    scale_offset_y: 50,
    hover_tag_offset_x: 20,
    hover_tag_offset_y: 20,
    canvas_width: 100000,
    canvas_height: 100000,
  },
  tables: {
    order_status_table: {
      show: true,
      columns: {
        id: true,
        logicalId: true,
        state: true,
        vehicleId: true,
        locationPickup: true,
        locationDropoff: true,
        locationMove: true,
        priority: true,
        carrierLabel: true,
        timeCreated: true,
        timeAssigned: true,
        origin: true,
        durationTotal: true,
        durationUnassigned: true,
        duration_from: true,
        durationLoad: true,
        duration_to: true,
        durationUnload: true,
        distancePickup: true,
        distanceDropoff: true,
        distanceMove: true,
        assignmentType: true,
      },
    },
    vehicle_status_table: {
      show: true,
      columns: {
        id: true,
        physicalId: true,
        logicalId: true,
        mode: true,
        canBePushed: true,
        orderOrigin: true,
        current: true,
        commandPoint: true,
        orderId: true,
        locationPickup: true,
        locationDropoff: true,
        locationMove: true,
        runtimeTotal: true,
        movingState: true,
        cargoState: true,
        errorList: true,
        isSensorStopped: true,
        isBlocked: true,
        distanceTotal: true,
      },
    },
    station_status_table: {
      show: false,
      columns: {
        id: true,
        physicalId: true,
        logicalId: true,
        point: true,
        direction: true,
        carrierType: true,
      },
    },
    buffer_status_table: {
      show: false,
      columns: {
        id: true,
        physicalId: true,
        logicalId: true,
        point: true,
        direction: true,
      },
    },
    order_playback_table: {
      show: true,
      columns: {
        id: true,
        logicalId: true,
        state: true,
        vehicleId: true,
        locationPickup: true,
        locationDropoff: true,
        locationMove: true,
        priority: true,
        carrierLabel: true,
        timeCreated: true,
        timeAssigned: true,
        origin: true,
        durationTotal: true,
        durationUnassigned: true,
        duration_from: true,
        durationLoad: true,
        duration_to: true,
        durationUnload: true,
        distancePickup: true,
        distanceDropoff: true,
        distanceMove: true,
        assignmentType: true,
      },
    },
    vehicle_playback_table: {
      show: true,
      columns: {
        id: true,
        physicalId: true,
        logicalId: true,
        mode: true,
        canBePushed: true,
        orderOrigin: true,
        curPoint: true,
        commandPoint: true,
        orderId: true,
        locationPickup: true,
        locationDropoff: true,
        locationMove: true,
        runtimeTotal: true,
        movingState: true,
        cargoState: true,
        errorList: true,
        isSensorStopped: true,
        isBlocked: true,
        distanceTotal: true,
      },
    },
    order_history_table: {
      show: true,
      columns: {
        historySourceId: true,
        logicalId: true,
        state: true,
        vehicleId: true,
        locationPickup: true,
        locationDropoff: true,
        locationMove: true,
        priority: true,
        carrierLabel: true,
        timeCreated: true,
        timeAssigned: true,
        timeVehicleArrived: true,
        timeLoadCompleted: true,
        timeUnloadStarted: true,
        timeUnloadCompleted: true,
        timeCompleted: true,
        timeAborted: true,
        timeFailed: true,
        origin: true,
        distancePickup: true,
        distanceDropoff: true,
        distanceMove: true,
        assignmentType: true,
        assignmentDetails: true,
      },
    },
    vehicle_history_table: {
      show: true,
      columns: {
        historySourceId: true,
        physicalId: true,
        logicalId: true,
        distanceTotal: true,
        runtimeTotal: true,
        type: true,
      },
    },
    alarm_history_table: {
      show: true,
      columns: {
        time: true,
        level: true,
        vehicleId: true,
        errorCode: true,
        description: true,
        timeResolved: true,
      },
    },
    alert_history_table: {
      show: true,
      columns: {
        time: true,
        level: true,
        tag: true,
        message: true,
        ackTime: true,
        ackBy: true,
      },
    },
  },
  permit_registration: true,
};
