export default {
	header: [
		{
			caption: 'Source명',
			dataField: 'sourceName',
		},
		{
			caption: '실패량',
			dataField: 'failureAmount',
			width: 80,
		},
	],
	body: [
		{
			sourceName: 'PORT_001asdfasdfasfsaf',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			sourceName: 'PORT_002',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_003',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_004',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			sourceName: 'PORT_005',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			sourceName: 'PORT_006',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_007',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			sourceName: 'PORT_008',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			sourceName: 'PORT_009',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			sourceName: 'PORT_010',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			sourceName: 'PORT_011',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			sourceName: 'PORT_012',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_013',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_014',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			sourceName: 'PORT_015',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			sourceName: 'PORT_016',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_017',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			sourceName: 'PORT_018',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			sourceName: 'PORT_019',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			sourceName: 'PORT_020',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			sourceName: 'PORT_021',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			sourceName: 'PORT_022',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_023',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			sourceName: 'PORT_024',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
	],
}
