export default {
	header: [
		{
			caption: 'Dest명',
			dataField: 'destName',
		},
		{
			caption: '실패량',
			dataField: 'failureAmount',
			width: 80,
		},
	],
	body: [
		{
			destName: 'PORT_101asdfasdfasfsaf',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			destName: 'PORT_102',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_103',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_104',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			destName: 'PORT_105',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			destName: 'PORT_106',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_107',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			destName: 'PORT_108',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			destName: 'PORT_109',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			destName: 'PORT_110',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			destName: 'PORT_111',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			destName: 'PORT_112',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_113',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_114',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			destName: 'PORT_115',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			destName: 'PORT_116',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_117',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			destName: 'PORT_118',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			destName: 'PORT_119',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			destName: 'PORT_120',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			destName: 'PORT_121',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			destName: 'PORT_122',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_123',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			destName: 'PORT_124',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
	],
}
