export default {
	header: [
		{
			caption: 'Vehicle명',
			dataField: 'vehicleName',
		},
		{
			caption: '실패량',
			dataField: 'failureAmount',
			width: 80,
		},
	],
	body: [
		{
			vehicleName: 'VEH_001asdfasdfasfsaf',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			vehicleName: 'VEH_002',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_003',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_004',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			vehicleName: 'VEH_005',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			vehicleName: 'VEH_006',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_007',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			vehicleName: 'VEH_008',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			vehicleName: 'VEH_009',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			vehicleName: 'VEH_010',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			vehicleName: 'VEH_011',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			vehicleName: 'VEH_012',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_013',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_014',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			vehicleName: 'VEH_015',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			vehicleName: 'VEH_016',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_017',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			vehicleName: 'VEH_018',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			vehicleName: 'VEH_019',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
		{
			vehicleName: 'VEH_020',
			failureAmount: 24,
			duplicate: 2,
			mismatch: 1,
			readfail: 5,
			dest: 1,
			source: 5,
			abort: 5,
			cancel: 5,
		},
		{
			vehicleName: 'VEH_021',
			failureAmount: 21,
			duplicate: 5,
			mismatch: 2,
			readfail: 3,
			dest: 2,
			source: 3,
			abort: 3,
			cancel: 3,
		},
		{
			vehicleName: 'VEH_022',
			failureAmount: 23,
			duplicate: 3,
			mismatch: 2,
			readfail: 4,
			dest: 2,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_023',
			failureAmount: 26,
			duplicate: 4,
			mismatch: 3,
			readfail: 4,
			dest: 3,
			source: 4,
			abort: 4,
			cancel: 4,
		},
		{
			vehicleName: 'VEH_024',
			failureAmount: 19,
			duplicate: 7,
			mismatch: 2,
			readfail: 2,
			dest: 2,
			source: 2,
			abort: 2,
			cancel: 2,
		},
	],
}
