<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <SpaRoot>frontend\packages\app\</SpaRoot>
    <PackageRoot>frontend\</PackageRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>

    <!-- Set this to true if you enable server-side prerendering -->
    <BuildServerSideRenderer>false</BuildServerSideRenderer>
    <UserSecretsId>b1d8b8c4-8e2c-4975-ad13-9b9ff069f67f</UserSecretsId>
    <StartupObject>OMSWeb.Program</StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>5</WarningLevel>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">Windows</DefineConstants>
    <DefineConstants Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">OSX</DefineConstants>
    <DefineConstants Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">Linux</DefineConstants>
    <FileVersion>1.0.0.3</FileVersion>
    <AssemblyVersion>1.0.0.3</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.2" />
    <PackageReference Include="Dapper" Version="2.0.78" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="20.1.3" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="2.8.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.12" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.12" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.0" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.6.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5" />
    <PackageReference Include="MQTTnet" Version="3.0.16" />
    <PackageReference Include="Npgsql" Version="5.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.11" />
    <PackageReference Include="Serilog" Version="2.11.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Map" Version="1.0.2" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Don't publish the SPA source files, but do show them in the project files list -->
    <Compile Remove="ClientApp-bak\**" />
    <Content Remove="$(SpaRoot)**" />
    <Content Remove="ClientApp-bak\**" />
    <EmbeddedResource Remove="ClientApp-bak\**" />
    <None Remove="$(SpaRoot)**" />
    <None Remove="ClientApp-bak\**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Remove="frontend\packages\app\src\app\models\carrier.model.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\models\fireshutter-status.model.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\models\fireshutter.model.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\models\query-result.model.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\models\transfer.model.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\modules\shared\dialogs\cps-reference-dialog.component.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\modules\shared\dialogs\success-dialog.component.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\modules\shared\dialogs\verify-dialog.component.ts" />
    <TypeScriptCompile Remove="frontend\packages\app\src\app\services\transfers.service.ts" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Temp\CopyFolder\" />
    <Folder Include="Temp\Zip\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(PackageRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(PackageRoot)" Command="yarn" />
    <Exec WorkingDirectory="$(PackageRoot)" Command="yarn build" />
  </Target>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(PackageRoot)" Command="yarn" />
    <Exec WorkingDirectory="$(PackageRoot)" Command="yarn build" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**; $(SpaRoot)dist-server\**" />
      <DistFiles Include="$(SpaRoot)node_modules\**" Condition="'$(BuildServerSideRenderer)' == 'true'" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties appsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>

</Project>