type ColorProperty =
  | 'background'
  | 'station'
  | 'stationDisabled'
  | 'buffer'
  | 'bufferDisabled'
  | 'point'
  | 'home'
  | 'normalSegment'
  | 'disabledSegment'
  | 'segmentDirection'
  | 'disconnectModeVehicleColor'
  | 'errorModeVehicleColor'
  | 'maintenanceModeVehicleColor'
  | 'manualModeVehicleColor'
  | 'idleModeVehicleColor'
  | 'runningModeVehicleColor'
  | 'cargoLoading'
  | 'cargoFull'
  | 'cargoUnloading'
  | 'fireshutterOpened'
  | 'fireshutterClosed'
  | 'mtlUnuse'
  | 'mtlUse'

export { ColorProperty }
