type ColorProperty =
	| 'background'
	| 'station'
	| 'stationDisabled'
	| 'buffer'
	| 'bufferDisabled'
	| 'point'
	| 'home'
	| 'normalSegment'
	| 'disabledSegment'
	| 'segmentDirection'
	| 'autoModeVehicle'
	| 'manualModeVehicle'
	| 'noneModeVehicle'
	| 'cargoLoading'
	| 'cargoFull'
	| 'cargoUnloading'
	| 'fireshutterOpened'
	| 'fireshutterClosed'
	| 'mtlUnuse'
	| 'mtlUse'

export { ColorProperty }
