type VisibleProperty =
	| 'vehicleNextLine'
	| 'vehicleFromOrderLine'
	| 'vehicleToOrderLine'
	| 'vehicleMoveOrderLine'
	| 'vehicleHomeivrLine'
	| 'segmentDirection'
	| 'pointLabel'
	| 'pointHome'
	| 'station'
	| 'buffer'
	| 'zcu'
	| 'group'
	| 'cluster'
	| 'cps'
	| 'fireshutter'
	| 'mtl'
	| 'minimap'
  | 'backdrop'

export { VisibleProperty }
