export const setting = {
  general: {
    reconnect_interval: 5000,
    table_update_interval: 800,
    split_ratio: 20,
  },
  history: {
    picker_increment: 10, // minutes
    picker_period: 6, // hours
    refresh_interval: 60, // seconds
  },
  segment_geometries: {
    D: {
      length: 1,
      short_side: 1,
      long_side: 1,
    },
    E: {
      length: 1085,
      short_side: 650,
      long_side: 650,
    },
    U: {
      length: 1870,
      short_side: 650,
      long_side: 1000,
    },
    S: {
      length: 1430,
      short_side: 610,
      long_side: 1200,
    },
  },
  map: {
    show_minimap: false,
    show_point_labels: false,
    show_direction_arrows: true,
    show_segments: true,
    show_stations: true,
    show_buffers: true,
    show_mtls: true,
    show_vehicles: true,
    show_groups: true,
    show_clusters: true,
    show_expected_path: false,
    vehicle_scale: 8,
    location_scale: 30,
    direction_arrow_scale: 5,
    map_rotation: 0,
    snap_to_grid_distance: 500, // mm
    minimum_segment_length: 500, // mm
    minimap_size_limit: 150, // pixels
    num_ticks: 20,
    vehicle_stale: 600, // s
    speed_straight: 3600, // m/s
    speed_curve: 800, // m/s
    scale_offset_x: 50,
    scale_offset_y: 50,
    hover_tag_offset_x: 20,
    hover_tag_offset_y: 20,
    canvas_width: 100000,
    canvas_height: 100000,
  },
  tables: {
    order_status_table: {
      show: true,
      columns: {
        id: true,
        logical_id: true,
        state: true,
        vehicle_id: true,
        location_pickup: true,
        location_dropoff: true,
        location_move: true,
        priority: true,
        carrier_label: true,
        time_created: true,
        time_assigned: true,
        origin: true,
        duration_total: true,
        duration_unassigned: true,
        duration_from: true,
        duration_load: true,
        duration_to: true,
        duration_unload: true,
        distance_pickup: true,
        distance_dropoff: true,
        distance_move: true,
        assignment_type: true,
      },
    },
    vehicle_status_table: {
      show: true,
      columns: {
        id: true,
        physical_id: true,
        logical_id: true,
        mode: true,
        can_be_pushed: true,
        order_origin: true,
        current: true,
        command_point: true,
        order_id: true,
        location_pickup: true,
        location_dropoff: true,
        location_move: true,
        runtime_total: true,
        moving_state: true,
        cargo_state: true,
        error_list: true,
        is_sensor_stopped: true,
        is_blocked: true,
        distance_total: true,
      },
    },
    station_status_table: {
      show: false,
      columns: {
        id: true,
        physical_id: true,
        logical_id: true,
        point: true,
        direction: true,
        carrier_type: true,
      },
    },
    buffer_status_table: {
      show: false,
      columns: {
        id: true,
        physical_id: true,
        logical_id: true,
        point: true,
        direction: true,
      },
    },
    order_playback_table: {
      show: true,
      columns: {
        id: true,
        logical_id: true,
        state: true,
        vehicle_id: true,
        location_pickup: true,
        location_dropoff: true,
        location_move: true,
        priority: true,
        carrier_label: true,
        time_created: true,
        time_assigned: true,
        origin: true,
        duration_total: true,
        duration_unassigned: true,
        duration_from: true,
        duration_load: true,
        duration_to: true,
        duration_unload: true,
        distance_pickup: true,
        distance_dropoff: true,
        distance_move: true,
        assignment_type: true,
      },
    },
    vehicle_playback_table: {
      show: true,
      columns: {
        id: true,
        physical_id: true,
        logical_id: true,
        mode: true,
        can_be_pushed: true,
        order_origin: true,
        cur_point: true,
        command_point: true,
        order_id: true,
        location_pickup: true,
        location_dropoff: true,
        location_move: true,
        runtime_total: true,
        moving_state: true,
        cargo_state: true,
        error_list: true,
        is_sensor_stopped: true,
        is_blocked: true,
        distance_total: true,
      },
    },
    order_history_table: {
      show: true,
      columns: {
        history_source_id: true,
        logical_id: true,
        state: true,
        vehicle_id: true,
        location_pickup: true,
        location_dropoff: true,
        location_move: true,
        priority: true,
        carrier_label: true,
        time_created: true,
        time_assigned: true,
        time_vehicle_arrived: true,
        time_load_completed: true,
        time_unload_started: true,
        time_unload_completed: true,
        time_completed: true,
        time_aborted: true,
        time_failed: true,
        origin: true,
        distance_pickup: true,
        distance_dropoff: true,
        distance_move: true,
        assignment_type: true,
        assignment_details: true,
      },
    },
    vehicle_history_table: {
      show: true,
      columns: {
        history_source_id: true,
        physical_id: true,
        logical_id: true,
        distance_total: true,
        runtime_total: true,
        type: true,
      },
    },
    alarm_history_table: {
      show: true,
      columns: {
        time: true,
        level: true,
        vehicle_id: true,
        error_code: true,
        description: true,
        time_resolved: true,
      },
    },
    alert_history_table: {
      show: true,
      columns: {
        time: true,
        level: true,
        tag: true,
        message: true,
        ack_time: true,
        ack_by: true,
      },
    },
  },
  permit_registration: true,
};
